"use client"

import { Sparkles, ArrowRight, Loader2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { useTransition } from "react"
import type { UnifiedNotes } from "@/types/models"
import { useAIGenerationStore } from "@/lib/ai-generation-store"

interface UnifiedNotesPreviewProps {
  chapterId: string
  notes: UnifiedNotes
}

export function UnifiedNotesPreview({ chapterId, notes }: UnifiedNotesPreviewProps) {
  const router = useRouter()
  const [isPending, startTransition] = useTransition()
  const { getLastGeneration } = useAIGenerationStore()
  const lastGen = getLastGeneration(chapterId)

  const handleOpenNotes = () => {
    startTransition(() => {
      router.push(`/chapter/${chapterId}/notes`)
    })
  }

  return (
    <div className="paper-card p-6 bg-ai-highlight/10 border-2 border-ai-highlight">
      <div className="flex items-start gap-4 mb-4">
        <div className="p-2 bg-ai-highlight rounded-lg">
          <Sparkles className="h-5 w-5 text-yellow-800" />
        </div>
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-1">
            <h3 className="font-serif text-xl font-bold text-ink">Unified Notes v{notes.version}</h3>
            <span className="text-sm text-muted">• Generated {notes.generatedAt}</span>
          </div>
          <p className="text-sm text-muted">
            {lastGen
              ? `Generated by ${lastGen.generatorRole} • Based on ${lastGen.contributionCount} contributions`
              : "AI-compiled study guide from all contributions"}
          </p>
        </div>
      </div>

      <div className="bg-card rounded-lg p-4 mb-4">
        <h4 className="font-semibold text-ink mb-2">Quick Overview:</h4>
        <ul className="space-y-2">
          {notes.overview.slice(0, 4).map((item, index) => (
            <li key={index} className="flex gap-2 items-start text-sm">
              <span className="flex-shrink-0 w-1.5 h-1.5 bg-primary rounded-full mt-1.5" />
              <span className="text-ink leading-relaxed">{item}</span>
            </li>
          ))}
          {notes.overview.length > 4 && (
            <li className="text-sm text-muted italic">+ {notes.overview.length - 4} more points...</li>
          )}
        </ul>
      </div>

      <Button className="w-full" onClick={handleOpenNotes} disabled={isPending}>
        {isPending ? (
          <>
            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
            Loading...
          </>
        ) : (
          <>
            Open Full Notes
            <ArrowRight className="h-4 w-4 ml-2" />
          </>
        )}
      </Button>
    </div>
  )
}
